# Generated by Django 5.2 on 2025-04-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_by_email',
            field=models.EmailField(blank=True, help_text='Email of the user who referred you.', max_length=255, null=True),
        ),
    ]
