# Generated by Django 5.2 on 2025-05-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_referred_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID of the user, if applicable.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the user, if applicable.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=50),
        ),
    ]
