# Generated by Django 5.2 on 2025-05-07 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_systems_generated_count', models.PositiveIntegerField(default=0, help_text='Number of NPC systems generated by the user.', verbose_name='NPC Systems Generated')),
                ('characters_generated_count', models.PositiveIntegerField(default=0, help_text='Number of characters generated by the user.', verbose_name='Characters Generated')),
                ('custom_generators_created_count', models.PositiveIntegerField(default=0, help_text='Number of custom random table generators created by the user.', verbose_name='Custom Generators Created')),
                ('ai_interfaced_characters_count', models.PositiveIntegerField(default=0, help_text='Number of characters for whom an AI interface/integration has been activated.', verbose_name='AI Interfaced Characters')),
                ('ai_image_generated_characters_count', models.PositiveIntegerField(default=0, help_text='Number of characters for whom an AI image has been generated.', verbose_name='AI Image Generated for Characters')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Usage',
                'verbose_name_plural': 'User Usages',
                'ordering': ['user__email'],
            },
        ),
    ]
