# Generated by Django 5.2 on 2025-05-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagetracking',
            name='character_avatars_uploaded_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of character avatars uploaded by the user.', verbose_name='Character Avatars Uploaded'),
        ),
        migrations.AddField(
            model_name='usagetracking',
            name='character_tokens_uploaded_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of character avatars uploaded by the user.', verbose_name='Character Avatars Uploaded'),
        ),
        migrations.AddField(
            model_name='usagetracking',
            name='custom_generator_tables_created_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of custom random table generators created by the user.', verbose_name='Custom Generators Created'),
        ),
    ]
