# Generated by Django 5.2 on 2025-04-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '__first__'),
        ('images', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(help_text='The character this image is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='character_images', to='characters.character')),
                ('image', models.ForeignKey(help_text='The image associated with the character.', on_delete=django.db.models.deletion.CASCADE, related_name='character_images', to='images.image')),
            ],
            options={
                'verbose_name': 'Character Image',
                'verbose_name_plural': 'Character Images',
                'ordering': ['character', 'id'],
            },
        ),
    ]
