# Generated by Django 5.2 on 2025-04-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0003_alter_archetype_options'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archetype',
            field=models.ForeignKey(blank=True, help_text='The archetype this character represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='archetype.archetype'),
        ),
    ]
