# Generated by Django 5.2 on 2025-05-26 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.CharField(blank=True, help_text='The occupation or profession of the character.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='rpg_class',
            field=models.CharField(blank=True, help_text='The rpg class, fighter, wizard, etc.', max_length=100, null=True),
        ),
    ]
