# Generated by Django 5.2 on 2025-04-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npc_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the table header (e.g., 'Combat', 'Magic', etc.).", max_length=50)),
                ('description', models.TextField(blank=True, help_text='A description of the table header.')),
                ('report_display_heading', models.CharField(blank=True, help_text='The heading to display in reports for this table header.', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='The order in which this table header should be displayed.')),
                ('number_of_rolls', models.PositiveIntegerField(default=1, help_text='The number of rolls to make when using this table header.')),
                ('roll_die_type', models.CharField(blank=True, help_text="The type of roll to make when using this table header (e.g., '1d6', '2d10').", max_length=50)),
                ('roll_mod', models.IntegerField(default=0, help_text='The modifier to apply to the roll when using this table header.')),
                ('random_gen_inclusision_level', models.PositiveSmallIntegerField(choices=[(1, 'Full Only'), (2, 'Medium'), (3, 'Quick')], default=2, help_text='The inclusion level for this table header.', verbose_name='Inclusion Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this table header was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this table header was last updated.')),
                ('npc_system', models.ForeignKey(help_text='The NPC system this table header belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='table_headers', to='npc_system.npcsystem')),
            ],
            options={
                'verbose_name': 'Table Header',
                'verbose_name_plural': 'Table Headers',
                'ordering': ['npc_system', 'display_order'],
                'unique_together': {('npc_system', 'name')},
            },
        ),
    ]
