# Generated by Django 5.2 on 2025-05-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_group', '0001_initial'),
        ('table_header', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableheader',
            options={'ordering': ['npc_system', 'table_group', 'display_order'], 'verbose_name': 'Table Header', 'verbose_name_plural': 'Table Headers'},
        ),
        migrations.AddField(
            model_name='tableheader',
            name='table_group',
            field=models.ForeignKey(default=1, help_text='The parent character group this sub-group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='table_group.tablegroup'),
            preserve_default=False,
        ),
    ]
