# Generated by Django 5.2 on 2025-05-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system', '0003_alter_owner_id_to_bigint'),
        ('table_header', '0002_alter_tableheader_options_tableheader_table_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableheader',
            name='npc_system',
            field=models.ForeignKey(help_text='The NPC system this table header belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='table_group', to='npc_system.npcsystem'),
        ),
    ]
