# Generated by Django 5.2 on 2025-05-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system', '0003_alter_owner_id_to_bigint'),
        ('table_group', '0001_initial'),
        ('table_header', '0004_alter_tableheader_npc_system'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableheader',
            unique_together={('npc_system', 'table_group', 'name')},
        ),
    ]
