# Generated by Django 5.2 on 2025-05-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_header', '0005_alter_tableheader_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableheader',
            unique_together=set(),
        ),
    ]
