# Generated by Django 5.2 on 2025-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system_rpg_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcsystemrpgclass',
            name='rpg_class_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Auto-incrementing ID within the context of the NPC system.', null=True),
        ),
    ]
