# Generated by Django 5.2 on 2025-04-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npc_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_group_name', models.CharField(help_text='The primary name of the character group for this NPC system.', max_length=50)),
                ('character_group_short_name', models.CharField(blank=True, help_text='An optional short name or abbreviation for the character group.', max_length=15, null=True)),
                ('description', models.TextField(blank=True, help_text="An optional description providing more details about the character group's purpose.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('npc_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='npc_system.npcsystem')),
            ],
            options={
                'verbose_name': 'Character Group',
                'verbose_name_plural': 'Character Groups',
                'ordering': ['npc_system', 'character_group_name'],
            },
        ),
    ]
