# Generated by Django 5.2 on 2025-04-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactergroup',
            name='character_group_name',
            field=models.CharField(help_text='The primary name of the character group for this NPC system.', max_length=75),
        ),
        migrations.AlterField(
            model_name='charactergroup',
            name='character_group_short_name',
            field=models.CharField(blank=True, help_text='An optional short name or abbreviation for the character group.', max_length=25, null=True),
        ),
    ]
