# Generated by Django 5.2 on 2025-05-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_group', '0001_initial'),
        ('npc_system', '0003_alter_owner_id_to_bigint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charactergroup',
            unique_together={('npc_system', 'character_group_name')},
        ),
    ]
