# Generated by Django 5.2 on 2025-04-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_group', '0002_alter_charactergroup_character_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactergroup',
            options={'ordering': ['npc_system', 'id'], 'verbose_name': 'Character Group', 'verbose_name_plural': 'Character Groups'},
        ),
    ]
