# Generated by Django 5.2 on 2025-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Alt Text'),
        ),
    ]
