# Generated by Django 5.2 on 2025-04-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_owner_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_url',
        ),
    ]
