# Generated by Django 5.2 on 2025-04-28 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_system_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('race_table_header', models.CharField(default='Race', help_text='The header for the race table', max_length=25)),
                ('profession_table_header', models.CharField(default='Profession', help_text='The header for the profession table', max_length=25)),
                ('rpg_class_table_header', models.CharField(default='Class', help_text='The header for the RPG class table', max_length=25)),
                ('standard_app_dsp', models.BooleanField(default=False)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(blank=True, default='', help_text='The genre of the NPC system, e.g., Fantasy, Sci-Fi, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genre.genre')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_systems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
