# Generated by Django 5.2 on 2025-04-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('npc_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcsystem',
            name='genre',
            field=models.ForeignKey(blank=True, default='', help_text='The genre of the NPC system, e.g., Fantasy, Sci-Fi, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genre.genre'),
        ),
    ]
