# Generated by Django 5.2 on 2025-05-05 19:00 # Adjust date/time as needed

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "npc_system",
            "0002_alter_npcsystem_owner",
        ),  # Depends on the previous migration
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # This AlterField operation forces Django to re-evaluate the field
        # against the database, potentially correcting the column type and FK constraint.
        migrations.AlterField(
            model_name="npcsystem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_systems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
