# Generated by Django 5.2 on 2025-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system', '0002_npcsystem_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcsystem',
            name='profession_table_header',
            field=models.CharField(default='Profession', help_text='The header for profession table', max_length=25),
        ),
        migrations.AddField(
            model_name='npcsystem',
            name='race_table_header',
            field=models.CharField(default='Race', help_text='The header for race table', max_length=25),
        ),
        migrations.AddField(
            model_name='npcsystem',
            name='rpg_class_table_header',
            field=models.CharField(default='RPG Class', help_text='The header for RPG class table', max_length=25),
        ),
    ]
