# Generated by Django 5.2 on 2025-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system', '0003_npcsystem_profession_table_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcsystem',
            name='profession_table_header',
            field=models.CharField(default='Profession', help_text='The header for the profession table', max_length=25),
        ),
        migrations.AlterField(
            model_name='npcsystem',
            name='race_table_header',
            field=models.CharField(default='Race', help_text='The header for the race table', max_length=25),
        ),
        migrations.AlterField(
            model_name='npcsystem',
            name='rpg_class_table_header',
            field=models.CharField(default='Class', help_text='The header for the RPG class table', max_length=25),
        ),
    ]
