# Generated by Django 5.2 on 2025-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system', '0003_alter_owner_id_to_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcsystem',
            name='npc_system_color',
            field=models.CharField(blank=True, help_text='A color code representing the NPC system, e.g., #FF5733', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='npcsystem',
            name='npc_system_color_name',
            field=models.CharField(blank=True, help_text="A name for the color representing the NPC system, e.g., 'Fire Red'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npcsystem',
            name='npc_system_icon',
            field=models.ImageField(blank=True, help_text='An icon representing the NPC system', null=True, upload_to='npc_systems/icons/'),
        ),
        migrations.AddField(
            model_name='npcsystem',
            name='npc_system_image',
            field=models.ImageField(blank=True, help_text='An image representing the NPC system', null=True, upload_to='npc_systems/images/'),
        ),
    ]
