# Generated by Django 5.2 on 2025-05-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_alter_genre_icon'),
        ('npc_system', '0004_npcsystem_npc_system_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcsystem',
            name='genre',
            field=models.ForeignKey(blank=True, default=None, help_text='The genre of the NPC system, e.g., Fantasy, Sci-Fi, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genre.genre'),
        ),
    ]
