"""
Django settings for pronto_npc_backend project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY", default="a-very-unsafe-default-key-for-dev-use-a-real-one-in-env"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# dj-rest-auth settings
REST_AUTH = {
    "USE_JWT": True,  # Tell dj-rest-auth to use JWT
    "JWT_AUTH_COOKIE": "my-access-token",  # Name for the access token cookie (for documentation)
    "JWT_AUTH_REFRESH_COOKIE": "my-refresh-token",  # Name for the refresh token cookie
    "JWT_AUTH_REFRESH_COOKIE_PATH": "/",  # Path for the refresh token cookie
    "JWT_AUTH_HTTPONLY": True,  # Refresh token cookie is HttpOnly
    "JWT_AUTH_SAMESITE": "Lax",  # SameSite attribute for the refresh token cookie
    "JWT_AUTH_SECURE": (
        not DEBUG
    ),  # Secure flag for the refresh token cookie (False in DEBUG)
    # Add other dj-rest-auth specific settings here if needed
}


ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

AUTH_USER_MODEL = "users.User"  # Custom user model

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",  # if using cookie storage
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SITE_ID = 1

# Optional: JWT settings (lifetimes, rotation)


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
    "ROTATE_REFRESH_TOKENS": False,  # Ensures refresh tokens are not rotated
    "BLACKLIST_AFTER_ROTATION": False,  # Not applicable if tokens are not rotated
}


# --- Update these allauth settings ---
SOCIALACCOUNT_EMAIL_VERIFICATION = "optional"  # Keep or change as needed

# New settings replacing deprecated ones:
ACCOUNT_LOGIN_METHODS = ["email"]  # Replaces ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_SIGNUP_FIELDS = {  # Using a dictionary for more clarity as per allauth docs
    "username": True,  # True means required
    "email": True,  # True means required
    "password": True,  # True means required
}
ACCOUNT_EMAIL_VERIFICATION = "optional"  # Or "optional" or "none". Explicitly set this.
ACCOUNT_UNIQUE_EMAIL = True  # Ensure emails are unique
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"

# * Deprecated settings (commented out):
# ACCOUNT_USERNAME_REQUIRED = True  # Explicitly set username requirement
# ACCOUNT_AUTHENTICATION_METHOD = "email"
# ACCOUNT_EMAIL_REQUIRED = True  # Ensure email is required

# --- End of updated allauth settings ---

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Third-party apps
    "drf_spectacular",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "simple_history",
    "corsheaders",
    # Custom Apps
    "npc_system",
    "images",
    "character_group",
    "character_sub_group",
    "archetype",
    "genre",
    "characters",
    "character_images",
    "npc_system_races",
    "npc_system_rpg_classes",
    "npc_system_professions",
    "table_group",
    "table_header",
    "table_items",
    "users",
    "profiles",
    "subscriptions",
    "age_category",
    "referrals",
    "usage_tracking",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Added for CORS - place high in the list
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React frontend
    "http://localhost:5173",  # Vite frontend
    "http://localhost:5174",  # Vite frontend alt
    "http://localhost:8000",  # Django dev server
    "http://127.0.0.1:8000",  # Django dev server (IP address)
    "http://localhost:8080",  # Swagger UI
]
# CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development
CORS_ALLOW_CREDENTIALS = True  # Uncomment if you need to allow credentials
# Email settings for development (print emails to console)
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

ROOT_URLCONF = "pronto_npc_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pronto_npc_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        # "HOST": "localhost",
        "PORT": config("DB_PORT", default="3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Add Authentication Backends if not already present (needed for allauth)
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Media files (User Uploads) - ADD THESE LINES
MEDIA_URL = (
    "/media/"  # URL prefix for media files served by Django dev server or web server
)
MEDIA_ROOT = os.path.join(
    BASE_DIR, "media"
)  # Absolute path to media directory where files will be stored

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SPECTACULAR_SETTINGS = {
    "TITLE": "Pronto NPC Backend API",
    "DESCRIPTION": "API for the Pronto NPC Backend application",
    "VERSION": "1.0.0",
    # This regex is used to determine the common path prefix for tag extraction.
    # By setting it to '/api/', drf-spectacular will use the next path segment
    # as the tag. e.g., /api/npc_system_races/ -> tag: npc_system_races
    "SCHEMA_PATH_PREFIX": r"/api/",
    # NOTE: Schema access is now controlled directly in `pronto_npc_backend/api_urls.py`
    # to ensure public access during development.
    # For production, you would remove the overrides in `api_urls.py` and use this:
    # "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"],
    "TAGS": [
        {
            "name": "age_category",
            "description": "Manage age categories for characters (e.g., Child, Adult, Elder).",
        },
        {
            "name": "archetype",
            "description": "Endpoints for managing character archetypes (e.g., Hero, Mentor, Villain).",
        },
        {
            "name": "characters",
            "description": "Operations related to individual characters.",
        },
        {
            "name": "genre",
            "description": "Endpoints for managing genres (e.g., Fantasy, Sci-Fi).",
        },
        {
            "name": "images",
            "description": "Endpoints for uploading and managing images for various models.",
        },
        {
            "name": "npc_system",
            "description": "Manage the core NPC systems that act as containers for characters, races, professions, random table generators, etc.",
        },
        {
            "name": "npc_system_rpg_classes",
            "description": "Endpoints for managing RPG classes (e.g., Fighter, Mage) associated with NPC systems.",
        },
        {
            "name": "npc_system_races",
            "description": "Endpoints for managing races associated with different NPC systems.",
        },
        {
            "name": "npc_system_professions",
            "description": "Endpoints for managing professions within NPC systems.",
        },
    ],
    "SERVE_INCLUDE_SCHEMA": False,  # Set to True to include schema in UI by default
    "SERVERS": [
        {
            "url": "http://localhost:8000",
            "description": "Local Development Server",
        }
    ],
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # Keep this False
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",  # Default stream is sys.stderr
            "level": "DEBUG",  # Ensure handler can process DEBUG messages
        },
    },
    "loggers": {
        "django.request": {  # Focus on request logging
            "handlers": ["console"],
            "level": "DEBUG",  # Log all request-related messages
            "propagate": False,  # Don't pass to parent loggers for now
        },
        "corsheaders": {  # Add this logger
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Add this line at the very end of the file:
# print(">>>> SETTINGS.PY WAS LOADED AND THIS PRINT STATEMENT IS FIRING <<<<")
