# Generated by Django 5.2 on 2025-04-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('expansion', models.BooleanField(default=False)),
                ('related_archetypes', models.TextField(blank=True, help_text='Comma-separated list of related archetypes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archetype',
                'verbose_name_plural': 'Archetypes',
                'ordering': ['expansion', 'name'],
            },
        ),
    ]
