# Generated by Django 5.2 on 2025-04-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'ordering': ['name'], 'verbose_name': 'Archetype', 'verbose_name_plural': 'Archetypes'},
        ),
        migrations.AddField(
            model_name='archetype',
            name='expansion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archetype',
            name='related_archetypes',
            field=models.TextField(blank=True, help_text='Comma-separated list of related archetypes.', null=True),
        ),
    ]
