# Generated by Django 5.2 on 2025-04-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archetype', '0002_alter_archetype_options_archetype_expansion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'ordering': ['expansion', 'name'], 'verbose_name': 'Archetype', 'verbose_name_plural': 'Archetypes'},
        ),
    ]
