# Generated by Django 5.2 on 2025-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_billing_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('storyteller', 'Storyteller'), ('architect', 'Architect')], max_length=50),
        ),
    ]
