# Generated by Django 5.2 on 2025-04-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npc_system', '0001_initial'),
        ('table_header', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Auto-incrementing ID within the context of the parent table header.', null=True)),
                ('value', models.TextField(help_text='The result text or value for this item.')),
                ('reroll_this_item', models.BooleanField(default=False, help_text='Indicates if rolling this specific item should trigger an immediate re-roll on the *same* table.')),
                ('description', models.TextField(blank=True, help_text='Optional description providing more context for the item value.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this item, not usually shown to the user.')),
                ('subsequent_table_roll', models.BooleanField(default=False, help_text='Indicates if rolling this item should trigger a roll on the linked subsequent table.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this item was last updated.')),
                ('npc_system', models.ForeignKey(help_text='The NPC system this table item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='table_items', to='npc_system.npcsystem')),
                ('subsequent_table', models.ForeignKey(blank=True, help_text="Optional: The next table header to roll on if 'subsequent_table_roll' is True.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_items_for_subsequent_roll', to='table_header.tableheader')),
                ('table_header', models.ForeignKey(help_text='The parent table header this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='table_items', to='table_header.tableheader')),
            ],
            options={
                'verbose_name': 'Table Item',
                'verbose_name_plural': 'Table Items',
                'ordering': ['npc_system', 'table_header_id', 'item_id'],
                'unique_together': {('table_header', 'item_id')},
            },
        ),
    ]
