# Generated by Django 5.2 on 2025-04-28 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableitem',
            options={'ordering': ['npc_system', 'table_header_id', 'item_id'], 'verbose_name': 'Table Item', 'verbose_name_plural': 'Table Items'},
        ),
        migrations.RemoveField(
            model_name='tableitem',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='tableitem',
            name='report_display_heading',
        ),
    ]
