# Generated by Django 5.2 on 2025-05-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agecategory',
            options={'ordering': ['age_category_name'], 'verbose_name': 'Age Category', 'verbose_name_plural': 'Age Categories'},
        ),
    ]
