# Generated by Django 5.2 on 2025-05-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age_category', '0002_alter_agecategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agecategory',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
