# Generated by Django 5.2 on 2025-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system_races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcsystemrace',
            name='race_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing ID within the context of the NPC system.', null=True),
        ),
    ]
