# Generated by Django 5.2 on 2025-04-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_system_races', '0002_alter_npcsystemrace_race_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcsystemrace',
            name='race_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Auto-incrementing ID within the context of the NPC system.', null=True),
        ),
    ]
