# Generated by Django 5.2 on 2025-04-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_sub_group_name', models.CharField(help_text='The primary name of the character sub-group.', max_length=75)),
                ('character_sub_group_short_name', models.CharField(blank=True, help_text='An optional short name or abbreviation for the character sub-group.', max_length=25, null=True)),
                ('description', models.TextField(blank=True, help_text="An optional description providing more details about the character sub-group's purpose.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_group', models.ForeignKey(help_text='The parent character group this sub-group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='character_group.charactergroup')),
            ],
            options={
                'verbose_name': 'Character Sub Group',
                'verbose_name_plural': 'Character Sub Groups',
                'ordering': ['character_group__npc_system', 'character_group', 'id'],
            },
        ),
    ]
