# Generated by Django 5.2 on 2025-05-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='genre_icons/'),
        ),
    ]
