# Generated by Django 5.2 on 2025-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_genre_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='genre_icons/'),
        ),
    ]
