# Generated by Django 5.2 on 2025-04-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegroup',
            name='number_of_rolls',
            field=models.PositiveIntegerField(default=1, help_text='The number of rolls to make when using this table group. The number of times to use this group of tables.'),
        ),
    ]
