# .github/workflows/django-ci.yml

name: Django CI

on:
  # push:
  #   branches: [main] # Trigger the workflow on push events to the main branch
  workflow_dispatch: {} # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Action to check out the repository code

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5" # Specify the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Install dependencies from requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py test # Execute the Django test suite
